version: '3.8'

services:
  postgres:
    container_name: postgres-data-base
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-review
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
